# Generated by Django 3.2.4 on 2021-07-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='libraryuser',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='libraryuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='staff_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
