# Generated by Django 3.2.4 on 2021-07-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('book', '0002_borrowedbooks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BorrowedBooks',
            new_name='BorrowedBook',
        ),
    ]
