# Generated by Django 3.2.4 on 2021-07-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_borrowedbooks_borrowedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='expected_return',
            field=models.DateField(),
        ),
    ]
